### ISSUE TITLE
on Mac OS

### ISSUE THREAD

**Issue by docyang** [srinivasrvaidya/Multi-Planar-Reconstruction-using-VTK#1]
Can this project run on mac os？
I run slicer.py  but got this error ：
rayCastFunction = vtk.vtkVolumeRayCastCompositeFunction()
AttributeError: 'module' object has no attribute 'vtkVolumeRayCastCompositeFunction'

can anyone help？

**Comment by chenjx1005** [comment]
Hi, how do you solve this problem?
